language: ruby

gemfile:
  - Gemfile
  - gemfiles/Gemfile.td-agent-2.3.5
  - gemfiles/Gemfile.td-agent-3.1.1
  - gemfiles/Gemfile.td-agent-3.2.0

env:
  - AWS_SDK_VERSION=DEFAULT
  - AWS_SDK_VERSION=1.3
  - AWS_SDK_VERSION=1.4
  - AWS_SDK_VERSION=1.5

matrix:
  exclude:
    - gemfile: Gemfile
      env: AWS_SDK_VERSION=1.3
    - gemfile: Gemfile
      env: AWS_SDK_VERSION=1.4
    - gemfile: Gemfile
      env: AWS_SDK_VERSION=1.5
  include:
    - rvm: 2.4.4
      gemfile: Gemfile
    - rvm: 2.1.10
      gemfile: gemfiles/Gemfile.td-agent-2.3.5
    - rvm: 2.4.2 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.1.1/config/projects/td-agent3.rb#L17
      gemfile: gemfiles/Gemfile.td-agent-3.1.1
    - rvm: 2.4.4 # https://github.com/treasure-data/omnibus-td-agent/blob/v3.2.0/config/projects/td-agent3.rb#L22
      gemfile: gemfiles/Gemfile.td-agent-3.2.0
  allow_failures:
    - env: AWS_SDK_VERSION=1.3
    - env: AWS_SDK_VERSION=1.4
    - env: AWS_SDK_VERSION=1.5
  fast_finish: true

script: bundle exec rake test

sudo: false
